import { Inter, Poppins } from "next/font/google";
import "./globals.css";

// import Navbar from "../components/Navbar";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });
// const poppins = Poppins({ subsets: ["latin"], weight: "900" });

export const metadata = {
  title: "Hola Nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
