### Listado invoices
GET https://668348284102471fa4c9a3dc.mockapi.io/api/v1/invoices

### Obteniendo un invoice por id
GET https://668348284102471fa4c9a3dc.mockapi.io/api/v1/invoices/81a8bd15-959a-4f6f-a5ae-920076fa1d5c

### Crear un nuevo invoice
POST https://668348284102471fa4c9a3dc.mockapi.io/api/v1/invoices
Content-Type: application/json

{
  "code": "XXYYZZ",
  "status": "pending",
  "bill": {
    "from": {
      "streetAddress": "19 Union Terrace",
      "city": "London",
      "postCode": "E13EZ",
      "country": "United Kingdom"
    },
    "to": {
      "client": {
        "name": "Victor Villazon",
        "email": "victor@mail.com"
      },
      "streetAddress": "99 Church Way",
      "city": "Bradford",
      "postCode": "CC19KK",
      "country": "United Kingdom"
    }
  },
  "invoice": {
    "date": "01 Oct 2021",
    "paymentTerms": "Next 30 Days",
    "project": {
      "description": "Graphic Design"
    },
    "grandTotal": 0.00,
    "currency": {
      "symbol": "$"
    },
    "items": [
    ]
  }
}